### ISSUE TITLE
Dataset release

### ISSUE THREAD

**Issue by Shrad1234** [Elvin-Yiming-Du/PerLTQA#1]
Dear Author,  
     Read your paper related to the dataset. currently working on a research focusing on robotic experiences and episodic memory retrieval because of which it would be great if I get the dataset as soon as possible.Waiting for the release of the same.

Thank you

**Comment by Elvin-Yiming-Du** [comment]
Thank you very much for your attention, we have uploaded the dataset, if you have any questions, please feel free to contact us.

**Comment by Elvin-Yiming-Du** [comment]
> Dear Author, Read your paper related to the dataset. currently working on a research focusing on robotic experiences and episodic memory retrieval because of which it would be great if I get the dataset as soon as possible.Waiting for the release of the same.
> 
> Thank you

Thank you very much for your attention, we have uploaded the dataset, if you have any questions, please feel free to contact us.
